I added an abstract, feel free to modify it.
hackseq/modular-assembly-hs18 pull request #3
Opened 2018-10-13 21:51 UTC by figalit

2018-10-13 22:00 UTC, sjackman requested changes
Thanks, Figali! Rather than a separate file, could you please add the abstract directly to the README.md?

2018-10-13 23:04 UTC, sjackman commented on README.md
> +
I suggest changing interchangeability to interoperability.

2018-10-13 23:04 UTC, figalit commented
Sure, how about now?

2018-10-13 23:05 UTC, sjackman commented on README.md
> +
Please delete this extra blank line.

2018-10-13 23:30 UTC, figalit commented on README.md
> +
Done.

2018-10-14 00:01 UTC, sjackman approved these changes

2018-10-14 00:02 UTC, merged